#!/bin/sh

# Init scripts are executed with "start" argument when system boots and with "stop" argument during shutdown
# So we need to check that it's boot state, not shutdown
[ -z "$1" ] || [ "$1" == "start" ] || exit 0

source "/etc/preinit"
script_init

ls  -l "$squashfs$gamepath" | grep 'CLV-' | awk '{ print $9 }' | while read gamecode; do
  if [ -f "$installpath/boxart/$gamecode.png" ]; then
    mount -o bind "$installpath/boxart/$gamecode.png" "$squashfs$gamepath/${gamecode}/${gamecode}.png"
  fi
  if [ -f "$installpath/boxart/${gamecode}_small.png" ]; then
    mount -o bind "$installpath/boxart/${gamecode}_small.png" "$squashfs$gamepath/${gamecode}/${gamecode}_small.png"
  fi
done < /dev/stdin
